# Exported from Render on 2026-07-27T11:21:26Z
version: "1"
projects:
- name: BubbleTea
  environments:
  - name: Production
    services:
    - type: web
      name: BubbleTea.-a
      runtime: python
      repo: https://github.com/mariamberuashvili/BubbleTea.-a
      plan: free
      envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      region: ohio
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
      autoDeployTrigger: commit
      rootDir: backend
